### ISSUE TITLE
Missing controllers: ballots, about, contact.

### ISSUE THREAD

**Issue by MelMcGee** [CLETeenHack/teen-vote#13]
We're missing controllers for ballots, about and contact.

**Comment by joelbyler** [comment]
@MelMcGee there is a ballots controller now.  it is here: https://github.com/CLETeenHack/teen-vote/blob/master/app/controllers/ballots_controller.rb

**Comment by MelMcGee** [comment]
Thanks, @joelbyler. I'll grab this one.

**Comment by MelMcGee** [comment]
Added controllers and merged PR.
