### ISSUE TITLE
Bootstrap conflict

### ISSUE THREAD

**Issue by MelMcGee** [CLETeenHack/teen-vote#14]
Hey @joelbyler, it looks like we have a conflict with bootstrap. I can reload my custom bootstrap files into assets/stylesheets, but I'm curious whether the gem you installed is grabbing it from the CDN (since I did a test run on replacing mine, and still didn't see it update). If so, I can look into how to locally remove that gem (I commented it out and did another bundle install without any change).

**Comment by joelbyler** [comment]
@MelMcGee I'll see if I can get that straightened out.  Sorry for the mixup.

**Comment by MelMcGee** [comment]
Looks good! Closing.
